#!/bin/bash

## Get my external IP
## linux - How can I get my external IP address in a shell script? - Unix & Linux Stack Exchange
## https://unix.stackexchange.com/questions/22615/how-can-i-get-my-external-ip-address-in-a-shell-script/344997#344997
## https://unix.stackexchange.com/a/344997/7286
## initial commit from https://github.com/mivk/myip

TIMEOUT=2   # seconds to wait for a reply before trying next server
VERBOSE=1   # prints which server was used
# path and file name for log file
MYIP_LOG="$PWD/myip.log"

dnslist=(
    "dig +short            myip.opendns.com        @resolver1.opendns.com"
    "dig +short            myip.opendns.com        @resolver2.opendns.com"
    "dig +short            myip.opendns.com        @resolver3.opendns.com"
    "dig +short            myip.opendns.com        @resolver4.opendns.com"
    "dig +short    -t txt  o-o.myaddr.l.google.com @ns1.google.com"
    "dig +short -4 -t a    whoami.akamai.net       @ns1-1.akamaitech.net"
    "dig +short            whoami.akamai.net       @ns1-1.akamaitech.net"
)

httplist=(
    4.ifcfg.me
    alma.ch/myip.cgi
    api.infoip.io/ip
    api.ipify.org
    bot.whatismyipaddress.com
    canhazip.com
    checkip.amazonaws.com
    eth0.me
    icanhazip.com
    ident.me
    ipecho.net/plain
    ipinfo.io/ip
    ipof.in/txt
    ip.tyk.nu
    l2.io/ip
    smart-ip.net/myip
    tnx.nl/ip
    wgetip.com
    whatismyip.akamai.com
	ipv4.wtfismyip.com/text
)

# For ipv6:	wtfismyip.com/text

function f_check_logfile () {
	if [ ! -f $MYIP_LOG ]
	then
		touch $MYIP_LOG
	fi
}


# function to shuffle the global array "array"
function f_shuffle() {
   local i tmp size max rand
   size=${#array[*]}
   max=$(( 32768 / size * size ))
   for ((i=size-1; i>0; i--)); do
      while (( (rand=$RANDOM) >= max )); do :; done
      rand=$(( rand % (i+1) ))
      tmp=${array[i]} array[i]=${array[rand]} array[rand]=$tmp
   done
}

f_check_logfile

## if we have dig and a list of dns methods, try that first
if hash dig 2>/dev/null && [ ${#dnslist[*]} -gt 0 ]; then
    eval array=( \"\${dnslist[@]}\" )
    f_shuffle

    for cmd in "${array[@]}"; do
        [ "$VERBOSE" == 1 ] && echo Trying: $cmd | tee -a $MYIP_LOG
        ip=$(timeout $TIMEOUT $cmd)
        if [ -n "$ip" ]; then
            echo $ip | tee -a $MYIP_LOG
            exit
        fi
    done
fi


# if we haven't succeeded with DNS, try HTTP

if [ ${#httplist[*]} == 0 ]; then
    echo "No hosts in httplist array!" >&2
    exit 1
fi

# use curl or wget, depending on which one we find
curl_or_wget=$(if hash curl 2>/dev/null; then echo "curl -s"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi);

if [ -z "$curl_or_wget" ]; then
    echo "Neither curl nor wget found. Cannot use http method." >&2
    exit 1
fi

eval array=( \"\${httplist[@]}\" )
f_shuffle

for url in "${array[@]}"; do
	[ "$VERBOSE" == 1 ] && echo Trying: $curl_or_wget "$url" | tee -a $MYIP_LOG
	ip=$(timeout $TIMEOUT $curl_or_wget "$url")
    if [ -n "$ip" ]; then
        echo $ip | tee -a $MYIP_LOG
        exit
    fi
done
